#!/usr/local/bin/php
<?php

// php sapi2 commanda opt1 opt2 opt3 opt4 --i -h
//print_r($argv);
/*
Array
(
    [0] => sapi2
    [1] => commanda
    [2] => opt1
    [3] => opt2
    [4] => opt3
    [5] => opt4
    [6] => --i
    [7] => -h
)
*/
//print_r($argc);
/*
8
*/
/*
start:

print("Введите номер записи и нажмите Enter. \n Номер записи: ");
$stdin = fopen("php://stdin", "r");
$record_num = fgets($stdin);
fclose($stdin);
print_r("Введите номер: " . $record_num);

goto start;
*/


$udata = ['name'=>'не указано','age'=>'не указано','password'=>'не указано'];
//function input(&$udata, $text, $field){}
//input($udata, "name", "");



print("Необходимо зарегистрироватся для использования сервиса. \nВаше имя: ");
$stdin = fopen("php://stdin", "r");
$udata['name'] = trim(fgets($stdin));
fclose($stdin);

print("Ваш возраст: ");
$stdin = fopen("php://stdin", "r");
$udata['age'] = trim(fgets($stdin));
fclose($stdin);

print("Ваш пароль: ");
$stdin = fopen("php://stdin", "r");
$udata['password'] = trim(fgets($stdin));
fclose($stdin);

print("\nПроверте и подтвердите введеных данных:");
print("\n - Имя: ".$udata['name']);
print("\n - Возраст: ".$udata['age']);
print("\n - Пароль: ".$udata['password']);

print("\nЕсли все верно, ");

confirm:

print("ведите Yes, или No для отметы, и нажмите Enter: ");
$stdin = fopen("php://stdin", "r");
$confirm = trim(fgets($stdin));
fclose($stdin);

switch (strtolower($confirm)) {
    case 'yas':
    case 'y':
    case 'да':
    case 'д':
        print("Вы успешно зарегестрированы.\n");
        break;

    case 'no':
    case 'n':
    case 'нет':
    case 'н':
        print("Вы отказались от зарегестрации.\n");
        break;
    
    default:
        print("Не верный ключ, ");
        goto confirm;
        break;
}

?>